apps/statushq/lib/statushq_web/router.ex
defmodule StatushqWeb.Router do
  use StatushqWeb, :router
  use Coherence.Router
  use Plug.ErrorHandler
  import StatushqWeb.Loaders
  import WithPro
  with_pro do: require StatushqProWeb.Router

  defp handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
    with_pro do: StatushqProWeb.ErrorReporter.report(conn, kind, reason, stacktrace)
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
    plug :load_my_pages
    plug :load_invitations
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StatushqWeb do
    pipe_through :browser
    coherence_routes()
  end

  scope "/", StatushqWeb do
    pipe_through :protected
    coherence_routes(:protected)
  end

  scope "/", StatushqWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/privacy", PageController, :privacy
    get "/terms", PageController, :terms
    resources "/status_pages", StatusPageController, except: [:index], param: "subdomain" do
      resources "/incidents", IncidentController
      post "/subscribe", StatusPageController, :subscribe, as: :subscribe
    end
  end

  pipeline :admin_layout do
    plug :put_layout, {StatushqWeb.Admin.LayoutView, :app}
  end

  scope "/admin", StatushqWeb.Admin, as: :admin do
    pipe_through [:protected, :admin_layout]
    get "/", StatusPageController, :index
    get "/profile", UserController, :edit
    get "/auth/request", AuthController, :request
    get "/auth/callback", AuthController, :callback
    with_pro do: StatushqProWeb.Router.private_routes()
    resources "/status_pages", StatusPageController, param: "subdomain" do
      get "/design", StatusPageController, :design, as: :design
      resources "/services", ServiceController
      resources "/members", UserStatusPageController, name: "members" do
        post "/accept_invite", UserStatusPageController, :accept_invite, as: :accept_invite
        post "/decline_invite", UserStatusPageController, :decline_invite, as: :decline_invite
      end

      resources "/incidents", IncidentController do
        resources "/activities", IncidentActivityController, name: "activity"
      end
    end
  end

  if Mix.env == :dev do
    scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, [base_path: "/dev/mailbox"]
    end
  end

  get "/", PageController, :index
end

apps/statushq/lib/statushq_web/views/admin/layout_view.ex
defmodule StatushqWeb.Admin.LayoutView do
  use StatushqWeb, :view
  import WithPro
  with_pro do: use StatushqProWeb.Admin.LayoutView
end

apps/statushq/lib/statushq_web/views/coherence/layout_view.ex
defmodule StatushqWeb.Coherence.LayoutView do
  use StatushqWeb.Coherence, :view
end

apps/statushq/lib/statushq_web/views/layout_view.ex
defmodule StatushqWeb.LayoutView do
  use StatushqWeb, :view

  def format_date conn, date, format, append_timezone \\ false do
    erl_date = NaiveDateTime.to_erl(date)
    # date = Timex.DateTime.from(erl_date)
    tzone = conn.assigns.status_page.time_zone
    {:ok, date} = Timex.format(Timex.Timezone.convert(date, tzone), format, :strftime)

    tz_abbrv = if append_timezone do
      tzone
      |> Tzdata.periods_for_time(:calendar.datetime_to_gregorian_seconds(erl_date), :wall)
      |> hd
      |> Map.get(:zone_abbr)
    else
      nil
    end

    date <> if(tz_abbrv, do: " #{tz_abbrv}", else: "")
  end

  def format_date conn, date do
    format_date(conn, date, "%B %eth, %Y at %H:%M", true)
  end

  def format_date_short conn, date do
    format_date(conn, date, "%b %eth, %Y %H:%M", true)
  end

  def format_date_time_shorter conn, date do
    format_date(conn, date, "%m/%d/%Y %H:%M")
  end

  def format_date_shorter conn, date do
    format_date(conn, date, "%m/%d/%Y")
  end

  def pluralize word, n do
    if n > 1, do: "#{word}s", else: word
  end

  def time_zones do
    now_secs = :calendar.datetime_to_gregorian_seconds(:calendar.universal_time)

    Tzdata.canonical_zone_list
    |> Enum.filter(fn(tz) -> !String.contains?(tz, ["GMT", "PST", "UCT"]) end)
    |> Enum.map(fn tz ->
      period = hd(Tzdata.periods_for_time(tz, now_secs, :wall))
      {tz, period[:zone_abbr], period[:utc_off] + period[:std_off]}
    end)
  end
end

apps/statushq/lib/statushq_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <link rel="shortcut icon" href="<%= static_url(@conn, "/images/statushq-logo.png") %>">

    <title><%= "#{@status_page.name} Status" %></title>
    <link rel="stylesheet" href="<%= static_url(@conn, "/css/status_page.css") %>">
    <style>
      <%= StatushqWeb.Admin.StatusPageView.page_styles(@status_page) %>
    </style>
    <%= render StatushqWeb.SharedView, "ga_code.html" %>
  </head>

  <body class="status-page">
    <div class="container-fluid">
      <div class="header clearfix">
        <div class="container">
          <div class="brand-name-container">
            <%= link to: StatushqWeb.StatusPageView.sd_url(status_page_url(@conn, :show, @status_page), @status_page),
              class: "brand-name"
            do %>
              <%= if @status_page.logo,
                do: img_tag(static_url(
                  @conn, StatushqWeb.Logo.url({@status_page.logo, @status_page}, :tiny)
                ), style: "height: 30px;")
              %>
              <%= @status_page.name %> Status
            <% end %>
          </div>
          <%= WithPro.disabled_for_plan(@conn, "free") do %>
            <%= if Statushq.is_mailgun_configured?() do %>
              <a href="#" class="subscribe">Subscribe</a>
            <% end %>
          <% end %>
        </div>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <div class="container">
          <%= render @view_module, @view_template, assigns %>
        </div>
      </main>

    </div> <!-- /container -->

    <footer class="footer">
      <div class="container">
        <%= link @status_page.name,
          to: if(String.contains?(@status_page.url, "http"),
                do: @status_page.url, else: "http://#{@status_page.url}")
        %>
        <%= link "Powered by Statuspal.io", to: "http://statuspal.io", class: "pull-right", target: :_blank %>
      </div>
    </footer>
    <script src="<%= static_url(@conn, "/js/status_page.js") %>"></script>
    <%= if WithPro.pro?(), do: render StatushqProWeb.SharedView, "cookies.html" %>
  </body>
</html>

apps/statushq/lib/statushq_web/templates/layout/email.html.eex
<html>
  <head>
    <title><%= @email.subject %></title>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>